# Default values for webapp.
# This is a YAML-formatted file.

# Number of pod replicas
replicaCount: 1

# Container image details
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

# Environmental vars for container (plain text)
env: {}
#  MY_VAR: 'value 123'

# Environmental vars from secrets
secretEnv: {}
#  SECRET_PWD:
#    secretName: mysecrets
#    secretKey: password

# Service config
service:
  type: ClusterIP
  port: 80
  targetPort: 8080 # Port container listens on

# Configure Ingress, switch on/off-able
ingress:
  enabled: false
  host: # MUST be provided if ingress enabled 
  tls:
    enabled: true
    secretName: # MUST be provided if tls enabled 
  annotations: {}

# Vauguely sensible defaults
resources: 
  limits:
    cpu: 1000m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

# Other pod config
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 20
  periodSeconds: 20

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}
